[package]
name = "blood-pressure-tracker-app"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.7", features = ["multipart"] }
axum-macros = "0.5.0"
bpm-ocr = "0.1.0"
serde = { version = "1.0.228", features = ["derive"] }
tokio = {version = "1.48.0", features = ["rt-multi-thread"]}
